services:
  - type: web
    name: organigrama-ssgg
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true